// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMDASiCzIR1ck138FAMJKmCb3N0Nmw0aw',
    appId: '1:11222946805:web:9e48d0de1b5b6dca13c6bc',
    messagingSenderId: '11222946805',
    projectId: 'pc-api-9131739738687432722-931',
    authDomain: 'pc-api-9131739738687432722-931.firebaseapp.com',
    storageBucket: 'pc-api-9131739738687432722-931.appspot.com',
    measurementId: 'G-XRX3HB3RLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDervpmYXev4zhSuKTgFC9SVnLfQYpRJNg',
    appId: '1:11222946805:android:f8e0a314d0e26cd213c6bc',
    messagingSenderId: '11222946805',
    projectId: 'pc-api-9131739738687432722-931',
    storageBucket: 'pc-api-9131739738687432722-931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5YgU8L63ZA7QAXtgdq6oqIipnScx33QI',
    appId: '1:11222946805:ios:1207cbfaec024e7513c6bc',
    messagingSenderId: '11222946805',
    projectId: 'pc-api-9131739738687432722-931',
    storageBucket: 'pc-api-9131739738687432722-931.appspot.com',
    iosClientId: '11222946805-1lsqojlf1mgrel74pgl9tqo1sv0vlv4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5YgU8L63ZA7QAXtgdq6oqIipnScx33QI',
    appId: '1:11222946805:ios:a6858ad7db23532e13c6bc',
    messagingSenderId: '11222946805',
    projectId: 'pc-api-9131739738687432722-931',
    storageBucket: 'pc-api-9131739738687432722-931.appspot.com',
    iosClientId: '11222946805-t2gtgreea8f528lkea2n7tl5oigb12le.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtTestApp.RunnerTests',
  );
}
